# Generated by Django 6.1.1 on 2026-10-07 07:48

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workflow", "0002_allow_cancel_before_advisor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # افزونه‌ی pgvector در Postgres (ایمیج pgvector/pgvector در docker-compose آن را دارد)
        pgvector.django.VectorExtension(),
        migrations.CreateModel(
            name="AssistantMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="پرسش")),
                ("answer", models.TextField(blank=True, verbose_name="پاسخ")),
                (
                    "sources",
                    models.JSONField(
                        blank=True, default=list, verbose_name="بندهای بازیابی\u200cشده"
                    ),
                ),
                ("ok", models.BooleanField(default=True, verbose_name="موفق")),
                ("error", models.CharField(blank=True, max_length=300)),
                ("model", models.CharField(blank=True, max_length=120)),
                (
                    "latency_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="زمان پاسخ (میلی\u200cثانیه)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "پرسش از دستیار",
                "verbose_name_plural": "پرسش\u200cهای دستیار",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "error",
                    models.CharField(blank=True, max_length=300, verbose_name="خطا"),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=120, verbose_name="مدل"),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="زمان درخواست"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پاسخ"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در حال بررسی"),
                            ("passed", "مطابق قالب"),
                            ("issues", "نیازمند توجه"),
                            ("error", "بررسی انجام نشد"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("items", models.JSONField(blank=True, default=list)),
                (
                    "version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation",
                        to="workflow.documentversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "اعتبارسنجی سند",
                "verbose_name_plural": "اعتبارسنجی\u200cهای سند",
            },
        ),
        migrations.CreateModel(
            name="PolicyChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_code",
                    models.CharField(
                        db_index=True, max_length=60, verbose_name="کد سند"
                    ),
                ),
                (
                    "doc_title",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="عنوان سند"
                    ),
                ),
                ("position", models.PositiveIntegerField(verbose_name="ترتیب")),
                (
                    "ref",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="بند مرجع"
                    ),
                ),
                ("text", models.TextField(verbose_name="متن")),
                ("embedding", pgvector.django.vector.VectorField()),
                (
                    "embedding_model",
                    models.CharField(max_length=120, verbose_name="مدل embedding"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "قطعه\u200cی پایگاه دانش",
                "verbose_name_plural": "قطعه\u200cهای پایگاه دانش",
                "ordering": ["doc_code", "position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("doc_code", "position"), name="unique_chunk_position"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SuggestionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "error",
                    models.CharField(blank=True, max_length=300, verbose_name="خطا"),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=120, verbose_name="مدل"),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="زمان درخواست"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پاسخ"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در حال آماده\u200cسازی"),
                            ("done", "آماده"),
                            ("error", "انجام نشد"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestion_run",
                        to="workflow.projectcase",
                    ),
                ),
            ],
            options={
                "verbose_name": "درخواست پیشنهاد داور",
                "verbose_name_plural": "درخواست\u200cهای پیشنهاد داور",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("event", "تغییر وضعیت"),
                            ("reminder", "یادآوری مهلت"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="مرحله\u200cی یادآوری"
                    ),
                ),
                ("subject", models.CharField(max_length=250, verbose_name="موضوع")),
                ("body", models.TextField(blank=True, verbose_name="متن")),
                (
                    "generated_by",
                    models.CharField(
                        blank=True,
                        help_text="llm = مدل زبانی، template = متن ثابت پشتیبان",
                        max_length=20,
                        verbose_name="تولیدکننده\u200cی متن",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "در صف ارسال"),
                            ("sent", "ارسال شد"),
                            ("failed", "ناموفق"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="workflow.projectcase",
                    ),
                ),
                (
                    "deadline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="workflow.deadline",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="workflow.caseevent",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="گیرنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "اعلان",
                "verbose_name_plural": "اعلان\u200cها",
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("event__isnull", False)),
                        fields=("event", "recipient"),
                        name="one_event_notice_per_recipient",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("deadline__isnull", False)),
                        fields=("deadline", "stage", "recipient"),
                        name="one_reminder_per_stage_per_recipient",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RefereeSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField(verbose_name="رتبه")),
                (
                    "score",
                    models.FloatField(
                        blank=True,
                        help_text="شباهت کسینوسی موضوع پیشنهاد با تخصص استاد؛ خالی = تخصص ثبت نشده",
                        null=True,
                        verbose_name="شباهت معنایی",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="توجیه")),
                (
                    "referee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to="agents.suggestionrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "داور پیشنهادی",
                "verbose_name_plural": "داوران پیشنهادی",
                "ordering": ["rank"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "referee"), name="one_row_per_referee"
                    )
                ],
            },
        ),
    ]
