# Generated by Django 6.1.1 on 2026-09-29 11:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='نام گروه آموزشی')),
            ],
            options={
                'verbose_name': 'گروه آموزشی',
                'verbose_name_plural': 'گروه\u200cهای آموزشی',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('student', 'دانشجو'), ('faculty', 'عضو هیئت\u200cعلمی'), ('edu_staff', 'کارشناس آموزش دانشکده'), ('external', 'نویسنده غیردانشجو')], default='student', max_length=10, verbose_name='نوع حساب')),
                ('is_department_head', models.BooleanField(default=False, verbose_name='مدیر گروه')),
                ('student_number', models.CharField(blank=True, max_length=20, verbose_name='شماره دانشجویی')),
                ('expertise', models.TextField(blank=True, help_text='متن آزاد؛ در فاز ۳ برای تطبیق معنایی (embedding) استفاده می\u200cشود', verbose_name='زمینه\u200cهای تخصصی')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='workflow.department', verbose_name='گروه آموزشی')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=250, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=250, verbose_name='عنوان انگلیسی')),
                ('academic_year', models.PositiveSmallIntegerField(verbose_name='سال تحصیلی (شمسی، مثلاً ۱۴۰۴)')),
                ('semester', models.CharField(choices=[('first', 'نیم\u200cسال اول'), ('second', 'نیم\u200cسال دوم'), ('summer', 'تابستان')], max_length=10, verbose_name='نیم\u200cسال ثبت\u200cنام')),
                ('registration_date', models.DateField(verbose_name='تاریخ ثبت\u200cنام پروژه')),
                ('state', models.CharField(choices=[('advisor_selection', 'انتخاب استاد راهنما'), ('drafting', 'تدوین پیشنهاد'), ('advisor_review', 'در انتظار تأیید استاد راهنما'), ('edu_registration', 'در انتظار ثبت در آموزش دانشکده'), ('referee_assignment', 'در انتظار تخصیص داور'), ('referee_review', 'در حال داوری'), ('revision', 'نیازمند اصلاح توسط دانشجو'), ('group_approval', 'در انتظار تصویب گروه'), ('council_approval', 'در انتظار تصویب شورای دانشکده'), ('in_progress', 'در حال اجرای پروژه'), ('thesis_advisor_review', 'پایان\u200cنامه در انتظار تأیید استاد راهنما'), ('thesis_submitted', 'پایان\u200cنامه تحویل شد؛ در انتظار تعیین زمان دفاع'), ('defense_scheduled', 'زمان و مکان دفاع تعیین شد'), ('completed', 'تکمیل\u200cشده'), ('rejected', 'ردشده'), ('cancelled', 'لغوشده')], db_index=True, default='advisor_selection', max_length=30, verbose_name='وضعیت')),
                ('edu_received_at', models.DateField(blank=True, null=True, verbose_name='تاریخ دریافت در آموزش دانشکده')),
                ('final_approved_at', models.DateField(blank=True, null=True, verbose_name='تاریخ تصویب نهایی')),
                ('thesis_submitted_at', models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل پایان\u200cنامه')),
                ('defense_date', models.DateField(blank=True, null=True, verbose_name='تاریخ دفاع')),
                ('defense_place', models.CharField(blank=True, max_length=200, verbose_name='محل دفاع')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='نمره')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advised_cases', to=settings.AUTH_USER_MODEL, verbose_name='استاد راهنما')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_cases', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو / نویسنده')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.department', verbose_name='گروه آموزشی')),
            ],
            options={
                'verbose_name': 'پرونده\u200cی پروژه',
                'verbose_name_plural': 'پرونده\u200cهای پروژه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('proposal', 'پیشنهاد پروژه'), ('thesis', 'پایان\u200cنامه')], max_length=10)),
                ('number', models.PositiveIntegerField(verbose_name='شماره\u200cی نسخه')),
                ('file', models.FileField(upload_to='cases/%Y/%m/')),
                ('note', models.CharField(blank=True, max_length=250, verbose_name='توضیح')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='workflow.projectcase')),
            ],
            options={
                'verbose_name': 'نسخه\u200cی سند',
                'verbose_name_plural': 'نسخه\u200cهای سند',
                'ordering': ['kind', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('proposal_submission', 'تحویل پیشنهاد به آموزش دانشکده'), ('group_review', 'پایان داوری در گروه آموزشی'), ('defense_earliest', 'زودترین تاریخ مجاز دفاع'), ('thesis_delivery', 'تحویل پایان\u200cنامه (۳ هفته پیش از مهلت نمره)'), ('grade_entry', 'مهلت درج نمره')], max_length=30)),
                ('due_date', models.DateField(verbose_name='تاریخ مهلت')),
                ('satisfied_at', models.DateField(blank=True, null=True, verbose_name='تاریخ انجام')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='workflow.projectcase')),
            ],
            options={
                'verbose_name': 'مهلت',
                'verbose_name_plural': 'مهلت\u200cها',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('from_state', models.CharField(choices=[('advisor_selection', 'انتخاب استاد راهنما'), ('drafting', 'تدوین پیشنهاد'), ('advisor_review', 'در انتظار تأیید استاد راهنما'), ('edu_registration', 'در انتظار ثبت در آموزش دانشکده'), ('referee_assignment', 'در انتظار تخصیص داور'), ('referee_review', 'در حال داوری'), ('revision', 'نیازمند اصلاح توسط دانشجو'), ('group_approval', 'در انتظار تصویب گروه'), ('council_approval', 'در انتظار تصویب شورای دانشکده'), ('in_progress', 'در حال اجرای پروژه'), ('thesis_advisor_review', 'پایان\u200cنامه در انتظار تأیید استاد راهنما'), ('thesis_submitted', 'پایان\u200cنامه تحویل شد؛ در انتظار تعیین زمان دفاع'), ('defense_scheduled', 'زمان و مکان دفاع تعیین شد'), ('completed', 'تکمیل\u200cشده'), ('rejected', 'ردشده'), ('cancelled', 'لغوشده')], max_length=30)),
                ('to_state', models.CharField(choices=[('advisor_selection', 'انتخاب استاد راهنما'), ('drafting', 'تدوین پیشنهاد'), ('advisor_review', 'در انتظار تأیید استاد راهنما'), ('edu_registration', 'در انتظار ثبت در آموزش دانشکده'), ('referee_assignment', 'در انتظار تخصیص داور'), ('referee_review', 'در حال داوری'), ('revision', 'نیازمند اصلاح توسط دانشجو'), ('group_approval', 'در انتظار تصویب گروه'), ('council_approval', 'در انتظار تصویب شورای دانشکده'), ('in_progress', 'در حال اجرای پروژه'), ('thesis_advisor_review', 'پایان\u200cنامه در انتظار تأیید استاد راهنما'), ('thesis_submitted', 'پایان\u200cنامه تحویل شد؛ در انتظار تعیین زمان دفاع'), ('defense_scheduled', 'زمان و مکان دفاع تعیین شد'), ('completed', 'تکمیل\u200cشده'), ('rejected', 'ردشده'), ('cancelled', 'لغوشده')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='خالی = رویداد سیستمی', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workflow.projectcase')),
            ],
            options={
                'verbose_name': 'رویداد',
                'verbose_name_plural': 'رویدادها',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RefereeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee_assignments', to='workflow.projectcase')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referee_assignments', to=settings.AUTH_USER_MODEL, verbose_name='داور')),
            ],
            options={
                'verbose_name': 'تخصیص داور',
                'verbose_name_plural': 'تخصیص\u200cهای داور',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', 'تأیید'), ('revise', 'بازگشت جهت اصلاح')], max_length=10)),
                ('comment', models.TextField(blank=True, verbose_name='نظر مکتوب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='workflow.refereeassignment')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='workflow.documentversion')),
            ],
            options={
                'verbose_name': 'نظر داور',
                'verbose_name_plural': 'نظرات داوران',
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_department_head', True)), fields=('department',), name='one_head_per_department'),
        ),
        migrations.AddConstraint(
            model_name='projectcase',
            constraint=models.CheckConstraint(condition=models.Q(('state', 'advisor_selection'), models.Q(('advisor__isnull', False), ('department__isnull', False)), _connector='OR'), name='advisor_required_after_selection'),
        ),
        migrations.AddConstraint(
            model_name='projectcase',
            constraint=models.CheckConstraint(condition=models.Q(('grade__isnull', True), models.Q(('grade__gte', 0), ('grade__lte', 20)), _connector='OR'), name='grade_between_0_and_20'),
        ),
        migrations.AddConstraint(
            model_name='projectcase',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['rejected', 'cancelled']), _negated=True), fields=('author', 'academic_year', 'semester'), name='one_active_case_per_author_term'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('case', 'kind', 'number'), name='unique_version_number'),
        ),
        migrations.AddConstraint(
            model_name='deadline',
            constraint=models.UniqueConstraint(fields=('case', 'kind'), name='one_deadline_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='refereeassignment',
            constraint=models.UniqueConstraint(fields=('case', 'referee'), name='unique_referee_per_case'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('assignment', 'version'), name='one_review_per_referee_per_version'),
        ),
    ]
