# Generated by Django 6.1.1 on 2026-10-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="projectcase",
            name="advisor_required_after_selection",
        ),
        migrations.AddConstraint(
            model_name="projectcase",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state__in", ["advisor_selection", "cancelled"]),
                    models.Q(("advisor__isnull", False), ("department__isnull", False)),
                    _connector="OR",
                ),
                name="advisor_required_after_selection",
            ),
        ),
    ]
